### ISSUE TITLE
Jade Release

### ISSUE THREAD

**Issue by rctoris** [ros-controls/ros_control#201] opened 2015-04-07 17:18 UTC
Just a friendly ping for a potential jade release to help some blocking packages for the upcoming beta.

**Comment by rethink-imcmahon** [comment] 2015-04-14 13:44
+1 for this

**Comment by adolfo-rt** [comment] 2015-04-15 07:58
I'll be spending time on the project in the next weeks, and will take a look at what's needed here. Because of the ROS distro transition, I'd like to take the opportunity to review which behavior and API changes would make sense to incorporate. More concretely, I'm thinking at least of #75 (API break), and https://github.com/ros-controls/ros_controllers/issues/48 (behavior change), which is long overdue.

**Comment by davetcoleman** [comment] 2015-04-15 16:53
Lets add https://github.com/ros-controls/ros_controllers/pull/142 also

**Comment by scpeters** [comment] 2015-04-22 23:03
+1, as [ros_control blocked the gazebo_ros_pkgs release for indigo](https://github.com/ros-simulation/gazebo_ros_pkgs/issues/179)

**Comment by adolfo-rt** [comment] 2015-04-23 07:48
Its likely that I'll have some cycles next week to look into this.

**Comment by wjwwood** [comment] 2015-04-23 22:12
+1, let me know if I can help.

**Comment by adolfo-rt** [comment] 2015-04-28 07:35
If `gazebo_ros_control` is moved to the `ros-controls` organization, (https://github.com/ros-simulation/gazebo_ros_pkgs/issues/179), then it would no longer block the release of `desktop-full`, and of Jade's beta.

Usually, the release of `ros_control` and friends has lagged a bit from the core packages. For indigo, we did not make it to the beta, but we did make it to the official release date. I'm trying to aim for a similar timeline with Jade.

**Comment by adolfo-rt** [comment] 2015-05-26 13:04
Quick update. My progress on this has been preempted until mid-June because of higher priority tasks. Most (if not all) of the development effort involving API changes has been done in #204, but I still have some TODOs before commiting to the release.

**Comment by DLu** [comment] 2015-07-02 02:18
Not to pile on, but +1 for new features of urdf_tutorial.

**Comment by bduffany** [comment] 2015-08-29 00:10
Any updates on this?

**Comment by adolfo-rt** [comment] 2015-09-04 16:41
Hi,
The deadline I've set to myself is ROScon. I'll be offline for three weeks starting on Tuesday Sept 8.

I'd like to fix #211, and optionally consider moving `gazebo_ros_control` to the ros-controls organization, since it's currently living in a limbo state. I'm actively working on that package, so I hope to have something solid for ROScon.

Thanks all for your prolonged patience. The jade release brings quite a few changes that have taken time to get right.

**Comment by werner-ne** [comment] 2015-09-28 15:43
Hi Adolfo, Is your personal deadline until end of this week still valid? thx

**Comment by adolfo-rt** [comment] 2015-10-01 13:15
Hi. I'm waiting for feedback on #211, which I consider a blocker for the Jade release.

**Comment by UltronDestroyer** [comment] 2015-11-03 19:57
Can we release this into Jade? It is blocking https://github.com/pr2-gbp/pr2_controllers-release/issues/1

**Comment by davetcoleman** [comment] 2015-11-04 17:33
+1, can we also fix the velocity controller's feed-forward term? 
https://github.com/ros-controls/ros_controllers/pull/142

**Comment by adolfo-rt** [comment] 2015-11-13 16:22
All blocking PRs for releasing the `ros_control` repo have been submitted (#218 and #210). After a pair of eyes gives them a +1, I'll merge and proceed with the pre-release → release sequence.

The idea is to get `ros_control` and `ros_controllers` released first. Then I'll see when I find another slot for `gazebo_ros_control`, which needs to be migrated to Gazebo 5. I don't know if there's a high overhead for this task or not. Hopefully not.

> +1, can we also fix the velocity controller's feed-forward term?
> ros-controls/ros_controllers#142

I commented directly in #142. It could make it as well.

**Comment by scpeters** [comment] 2015-11-13 17:42
Regarding `gazebo_ros_control` and `gazebo5`, there's two concerns:
- gazebo5 uses c++11, so anything downstream that builds plugins needs to use the `GAZEBO_CXX_FLAGS`, but that should already be fixed ( https://github.com/ros-simulation/gazebo_ros_pkgs/commit/4d46186a2fa20bdc59403bfb34271a672021361b )
- We changed the behavior of `Joint::SetVelocity` and `Joint::SetMaxForce`, so anything using velocity commands (instead of torque commands) will need to use `Joint::SetParam("vel")` and `Joint::SetParam("max_force")`. I'm not sure if `gazebo_ros_control` uses a velocity control interface.

**Comment by adolfo-rt** [comment] 2015-11-18 08:37
Thanks @scpeters. The second point has not yet been addressed, and `gazebo_ros_control` does use a velocity control interface.

**Comment by adolfo-rt** [comment] 2015-11-20 23:30
FYI,
https://github.com/ros/rosdistro/pull/9849
https://github.com/ros/rosdistro/pull/9850

Pending feature requests can be merged as patch releases on top of 0.10

**Comment by adolfo-rt** [comment] 2015-11-21 00:18
I'll push some release notes to the robot control SIG in the coming days.

**Comment by davetcoleman** [comment] 2015-11-22 08:13
Thanks @adolfo-rt !

**Comment by mathias-luedtke** [comment] 2015-12-01 17:50
Now that the jade release is on its way, what about a new indigo release?

**Comment by bmagyar** [comment] 2015-12-02 20:55
+1
The `diff_drive_controller` could definitely use one!

I'm willing to do the release procedure once all lights are green.

**Comment by adolfo-rt** [comment] 2015-12-04 15:56
Yes, on the agenda. I'm currently getting a failed test in `diff_drive_controller`. Can't release `ros_controllers` like that:

```
[diff_drive_controller.rosunit-diff_drive_limits_test/testAngularJerkLimits][FAILURE]
/home/adolfo/ros_control_ws/src/ros_controllers/diff_drive_controller/test/diff_drive_limits_test.cpp:150
The difference between new_odom.twist.twist.angular.z and 0.7 is 0.060075881205914228, which exceeds JERK_ANGULAR_VELOCITY_TOLERANCE, where
new_odom.twist.twist.angular.z evaluates to 0.76007588120591418,
0.7 evaluates to 0.69999999999999996, and
JERK_ANGULAR_VELOCITY_TOLERANCE evaluates to 0.050000000000000003.
```

I don't have time right now to dig into this. So if someone can reproduce that would accelerate the release.

**Comment by scpeters** [comment] 2015-12-04 19:07
I'll try to take a look. It may be related to the first point I made above.

**Comment by efernandez** [comment] 2015-12-06 23:46
That test from the `diff_drive_controller` is probably not robust enough to time differences when it computes the relative odometry: it works for me (I can't reproduce it) and it works on Travis.

Anyway, I'm going to look into it to make it more robust to time differences. If that's not the reason, I'll increase the tolerance on the test for now, as this feature (jerk limits) shouldn't be blocking a release.

**Comment by adolfo-rt** [comment] 2016-02-12 19:59
Indigo:

https://github.com/ros/rosdistro/pull/10491
https://github.com/ros/rosdistro/pull/10492

I still see that diff drive test flakiness in my box, but pulled the trigger anyway.

**Comment by efernandez** [comment] 2016-02-12 23:26
@adolfo-rt I have some WIP branch for them, but I can relax that test that sometimes fails meanwhile.

In my branch (I repeat still WIP) I have an exhaustive set of unit tests that all pass, but curiously, that rostest doesn't, so I think it's related with some timing issue between runs.

**Comment by adolfo-rt** [comment] 2016-02-15 09:04
@efernandez Let's bring in those changes in the next patch release. This one is already out.
https://github.com/ros/rosdistro/pull/10497
https://github.com/ros/rosdistro/pull/10498

**Closed as completed by adolfo-rt** 2016-02-15 09:04 UTC
Labels: ready

**Comment by sytelus** [comment] 2016-07-23 10:18
Looks like this issue is closed but there is still no ros-jade-gazebo-ros-control package :(.

`sudo apt-get install ros-jade-gazebo-ros-control`
`E: Unable to locate package ros-jade-gazebo-ros-control`

Any idea how to get ros-control package on Jade? This seems to be the only thing stopping to make gazebo demo work on Jade.

**Comment by bmagyar** [comment] 2016-07-25 14:27
Are you sure everything is ok with your installation?
https://github.com/ros/rosdistro/blob/master/jade/distribution.yaml#L1104
I checked packages.ros.org but couldn't find it there... it's weird. 
Could you bring up this question here please? http://discourse.ros.org/c/release
I don't have an installation to test this on at the moment.

**Comment by wjwwood** [comment] 2016-07-25 17:38
Jade hasn't been synced with Public since `gazebo_ros_pkgs` was released with `gazebo_ros_control` included: http://repositories.ros.org/status_page/ros_jade_default.html?q=gazebo_ros_control

**Comment by bjornite** [comment] 2016-07-25 18:16
Does that mean this issue will go away soon?

**Comment by wjwwood** [comment] 2016-07-25 18:17
It means that the package will be available next time we sync Jade to the public repositories. I don't know when that will be, but probably within the next month.

You could use the shadow fixed repository and get the package now if you wanted: http://wiki.ros.org/ShadowRepository
